// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: core/proxy/nextv1/config.proto

package nextv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_core_proxy_nextv1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Account) ProtoMessage()    {}
func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_core_proxy_nextv1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_core_proxy_nextv1_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Config struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxTimeSkewSeconds uint32                 `protobuf:"varint,1,opt,name=max_time_skew_seconds,json=maxTimeSkewSeconds,proto3" json:"max_time_skew_seconds,omitempty"`
	ReplayCapacity     uint32                 `protobuf:"varint,2,opt,name=replay_capacity,json=replayCapacity,proto3" json:"replay_capacity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_core_proxy_nextv1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Config) ProtoMessage()    {}
func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_core_proxy_nextv1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_core_proxy_nextv1_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetMaxTimeSkewSeconds() uint32 {
	if x != nil {
		return x.MaxTimeSkewSeconds
	}
	return 0
}

func (x *Config) GetReplayCapacity() uint32 {
	if x != nil {
		return x.ReplayCapacity
	}
	return 0
}

var File_core_proxy_nextv1_config_proto protoreflect.FileDescriptor

const file_core_proxy_nextv1_config_proto_rawDesc = "" +
	"\n" +
	"\x1ecore/proxy/nextv1/config.proto\x12\x18v2node.core.proxy.nextv1\"%\n" +
	"\aAccount\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"d\n" +
	"\x06Config\x121\n" +
	"\x15max_time_skew_seconds\x18\x01 \x01(\rR\x12maxTimeSkewSeconds\x12'\n" +
	"\x0freplay_capacity\x18\x02 \x01(\rR\x0ereplayCapacityB-Z+github.com/wyx2685/v2node/core/proxy/nextv1b\x06proto3"

var (
	file_core_proxy_nextv1_config_proto_rawDescOnce sync.Once
	file_core_proxy_nextv1_config_proto_rawDescData []byte
)

func file_core_proxy_nextv1_config_proto_rawDescGZIP() []byte {
	file_core_proxy_nextv1_config_proto_rawDescOnce.Do(func() {
		file_core_proxy_nextv1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proxy_nextv1_config_proto_rawDesc), len(file_core_proxy_nextv1_config_proto_rawDesc)))
	})
	return file_core_proxy_nextv1_config_proto_rawDescData
}

var file_core_proxy_nextv1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_proxy_nextv1_config_proto_goTypes = []any{
	(*Account)(nil),
	(*Config)(nil),
}
var file_core_proxy_nextv1_config_proto_depIdxs = []int32{
	0,
	0,
	0,
	0,
	0,
}

func init() { file_core_proxy_nextv1_config_proto_init() }
func file_core_proxy_nextv1_config_proto_init() {
	if File_core_proxy_nextv1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proxy_nextv1_config_proto_rawDesc), len(file_core_proxy_nextv1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_proxy_nextv1_config_proto_goTypes,
		DependencyIndexes: file_core_proxy_nextv1_config_proto_depIdxs,
		MessageInfos:      file_core_proxy_nextv1_config_proto_msgTypes,
	}.Build()
	File_core_proxy_nextv1_config_proto = out.File
	file_core_proxy_nextv1_config_proto_goTypes = nil
	file_core_proxy_nextv1_config_proto_depIdxs = nil
}
